signingKeyId=79A91005
signingKey=-----BEGIN PGP PRIVATE KEY BLOCK-----\nlIYEaN194BYJKwYBBAHaRw8BAQdAX3eHuZLVYb96GcrOAUvY1ENfBGKACmm+8e/4\nGGRgtvb+BwMC7wkIlW8DiV/0RvQZSI8WG6MHqsjJxgDWtw1QZUgDLjP4iNx4/uOs\nW7JGmb/quaGb3/nkP97L3LoRxT0wV11bF/KRXseQcBzdkUW0F5Ore7QmU3llZCBG\nYXJoYW4gQWxpIDxmLnN5ZWQuYWxpQGdtYWlsLmNvbT6ImQQTFgoAQRYhBDbB75WG\nRSe7s5we1701dVzYqTc1BQJo3X3gAhsDBQkFo5qABQsJCAcCAiICBhUKCQgLAgQW\nAgMBAh4HAheAAAoJEL01dVzYqTc1ZmQBAMiJCq5tkjUdjN9gaHDRDuHSpVbcruzm\ngcUWZqYz6f4gAQD3vGGoJtN1lJ0D7Af7ktjyPoqtq6AemsGXveV8SXHfAZyLBGjd\nfeASCisGAQQBl1UBBQEBB0DlYuq7nyUFmNtA1Php+k/V7VpLCUsqLxnSrpwQzaEG\nKgMBCAf+BwMCOlra2xhB32f0An5TRzNXhiW+5qaO+9jlqEl9bp/0O1ET6bpKNGqw\nc6a5t+ohmxY3OGHvEmH/ox8C/cp1kWEhlsSq9xQzJNyKrBk67p43jIh+BBgWCgAm\nFiEENsHvlYZFJ7uznB7XvTV1XNipNzUFAmjdfeACGwwFCQWjmoAACgkQvTV1XNip\nNzXljgEAy95BVmPkkfzmbU8CH2QVtei5G0AmreGJSgycr/a31GwBAI6IVDxrFCco\nBzG6FAtk6ZJfBTy1qXFPGPujNjB/rocE\n-----END PGP PRIVATE KEY BLOCK-----
signingPassword=9p8o7i6U$
